controller_frequency: 7

TrajectoryPlannerROS:

  holonomic_robot: false
  sim_time: 1.0
  meter_scoring: true
  pdist_scale: 0.6
  max_vel_x: 0.8
  min_vel_x: 0.2
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.4

  acc_lim_x: 2.4
  acc_lim_y: 2.4
  acc_lim_theta: 3.4

# Goal Tolerance Parameters
  yaw_goal_tolerance:           0.10
  xy_goal_tolerance:            0.10
  latch_xy_goal_tolerance:      true
