map_type: costmap

max_obstacle_height: 0.7
obstacle_range: 5.5
raytrace_range: 8.0
transform_tolerance: 0.4
inflation_radius: 0.7


observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /explo_bot/laser/scan, marking: true, clearing: true}
