TrajectoryPlannerROS:

  holonomic_robot: false
  sim_time: 1.0
  meter_scoring: false
  pdist_scale: 0.6
  yaw_goal_tolerance: 0.1
  xy_goal_tolerance: 0.1
  controller_frequency: 10
  max_vel_x: 0.6
  min_vel_x: 0.15
  max_vel_theta: 1.2
  min_vel_theta: -1.2
  min_in_place_vel_theta: 0.5
  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 2.8
