controller_frequency: 7
TrajectoryPlannerROS:

  holonomic_robot: false
  sim_time: 1.0
  meter_scoring: false
  yaw_goal_tolerance: 0.05
  xy_goal_tolerance: 0.05

  max_vel_x: 0.4
  min_vel_x: 0.1
  max_vel_theta: 1.0
  min_vel_theta: -1.0
  min_in_place_vel_theta: 0.35
  acc_lim_x: 2.0
  acc_lim_y: 2.0
  acc_lim_theta: 2.8
